export const LOCALES_PREFIXES = [
  'actions',
  'main',
  'common',
  'common.sideNav',
  'common.topNav',
  'pages',
  'pages.notFound',
  'pages.unauthorized',
  'flow',
  'flow.controls',
  'listings',
  'listings.raidTable',
  'listings.raidTable.header',
  'main.root',
  'main.id',
] as const;
